" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" search stuff
set incsearch     " do incremental searching
set hlsearch      " highlight search
set ignorecase    " case insensitive search
set smartcase

" NerdTree
:noremap ,n :NERDTreeToggle<CR>

" Colors
colorscheme molokai
syntax on
if !has('gui_running')
	set t_Co=256
endif

" easier window navigation
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

nmap <leader>l :set list!<CR>
set listchars=tab:▸\ ,eol:¬
set number
set tabstop=2
set shiftwidth=2
set softtabstop=2
set mouse=a
